[build]
  base = "frontend/hirable-web"
  command = "npm run build"
  publish = "dist/hirable-web/browser"

[[redirects]]
  from = "/api/*"
  to = "http://18.220.87.96:8080/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
